# syntax=docker/dockerfile:1

FROM sileriumphp-web-app:latest

WORKDIR /var/www

USER root

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

RUN apt update && apt install -y --no-install-recommends \
    apache2-dev \
    curl \
    unzip \
    libpq-dev \
    libonig-dev \
    libssl-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    libicu-dev \
    libzip-dev  && \
    install-php-extensions xdebug && \
    composer install

COPY ./docker/silerium-dev.conf /etc/apache2/sites-available
COPY ./docker/silerium_proxy.conf /etc/apache2/sites-available

RUN a2dissite silerium && \
    a2dissite 000-default && \
    a2ensite silerium-dev

RUN /usr/local/bin/prod.sh && rm /usr/local/bin/prod.sh

COPY ./docker/entrypoints/dev.sh /usr/local/bin
COPY ./docker/entrypoints/test.sh /usr/local/bin
RUN chmod 775 /usr/local/bin/dev.sh && \
chmod 775 /usr/local/bin/test.sh

EXPOSE 8080

ENTRYPOINT [ "/usr/local/bin/dev.sh" ]

CMD [ "apachectl", "-D", "FOREGROUND" ]