services:
  web-app:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
      - 8080:80
    healthcheck:
      test: ["CMD", "curl", "-kf", "http://localhost"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    volumes:
      - ./:/var/www/
      - ./.env.testing:/var/www/.env
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/silerium-dev.conf:/etc/apache2/sites-enabled/silerium-dev.conf:ro
      - ./docker/mysql_custom.cnf:/etc/mysql/conf.d/mysql_custom.cnf:ro
    networks:
      - backend-testing
      - cache-testing
  dbgate:
    image: dbgate/dbgate
    restart: unless-stopped
    ports:
      - 8081:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      CONNECTIONS: mysql

      LABEL_mysql: MySql
      SERVER_mysql: db
      DATABASE_mysql: sileriumdb_testing
      USER_mysql: app
      PASSWORD_mysql: SAmsuNG123sileriumdb
      PORT_mysql: 3306
      ENGINE_mysql: mysql@dbgate-plugin-mysql

      LOGIN: app
      PASSWORD: SAmsuNG123sileriumdb
      LOGIN_PERMISSIONS_app: "*"

    volumes:
      - dbgate-testing-data:/root/.dbgate
    networks:
      - backend-testing
    depends_on:
      db:
        condition: service_healthy
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8025"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - 8825:8025
      - 1125:1025
    networks:
      - backend-testing
    depends_on:
      web-app:
        condition: service_healthy
  db:
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - MYSQL_ROOT_PASSWORD=SAmsuNG123sileriumdb
      - MYSQL_DATABASE=sileriumdb_testing
      - LANG=C.UTF_8
    command: 
    - --character-set-server=utf8mb4 
    - --collation-server=utf8mb4_unicode_ci
    volumes:
      - backend-testing-data:/var/lib/mysql/
    networks:
      - backend-testing
  cache:
    image: memcached:1.6.24
    restart: unless-stopped
    command:
      - --conn-limit=1024
      - --threads=4
      - --memory-limit=4096
    networks:
      - cache
networks:
  backend-testing:
  cache-testing:
volumes:
  backend-testing-data:
  dbgate-testing-data:
    driver: local