# syntax=docker/dockerfile:1

FROM php:8.1-apache as base

WORKDIR /var/www

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN apt update && apt install -y \
npm \
mariadb-client && \
install-php-extensions @composer \
calendar \
bcmath \
ffi \
gd \
gettext \
igbinary \
imagick \
imap \
intl \
memcached \
msgpack \
mysqli \
pcntl \
pdo_mysql \
shmop \
soap \
sockets \
sysvmsg \
sysvsem \
sysvshm \
xmlrpc \
xsl \
zip \
opcache

COPY . .

RUN composer install --no-dev --optimize-autoloader --no-interaction --no-progress --prefer-dist && \
composer dump-autoload && \
npm install --dev && \
npm run build && \
chown root:www-data -R . && \
find . -type f -exec chmod 664 {} + && \
find . -type d -exec chmod 775 {} + && \
chmod 775 env_conf/laravel.sh

COPY ./env_conf/mysql_custom.cnf /etc/mysql/conf.d

FROM base AS apache2

RUN apt update && apt install -y apache2-dev unzip

ADD --chmod=0775 https://github.com/nmaier/mod_xsendfile/archive/refs/heads/master.zip .

ENV APACHE_DIR=/etc/apache2

RUN mkdir ${APACHE_DIR}/cert

COPY --from=base /var/www/env_conf .
COPY ./env_conf/silerium.conf ${APACHE_DIR}/sites-available
COPY ./env_conf/silerium.crt ${APACHE_DIR}/cert
COPY ./env_conf/silerium.key ${APACHE_DIR}/cert

RUN unzip master.zip && \
apxs -cia mod_xsendfile-master/mod_xsendfile.c && \
a2enmod expires && \
a2enmod cache && \
a2enmod cache_disk && \
a2enmod cache_socache && \
a2enmod headers && \
a2enmod socache_memcache && \
a2enmod ssl && \
a2enmod rewrite && \
a2ensite silerium

RUN rm -r mod_xsendfile-master && rm master.zip

EXPOSE 4443

CMD ["apachectl", "-D", "FOREGROUND"]